DELIMITER //
DROP PROCEDURE IF EXISTS createBlogUrl // 

CREATE PROCEDURE createBlogUrl(IN BlogIdIn int, IN UrlIn VARCHAR(90))
BEGIN
UPDATE blog SET Url=UrlIn WHERE BlogId = BlogIdIn;
SELECT LAST_INSERT_ID();
END//
DELIMITER ;
